# Generated by Django 5.1.1 on 2024-10-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_list', models.CharField(max_length=100)),
                ('task_detail', models.CharField(max_length=100)),
                ('task_create', models.CharField(max_length=100)),
                ('task_update', models.CharField(max_length=100)),
                ('task_select_update', models.CharField(max_length=100)),
                ('task_delete', models.CharField(max_length=100)),
            ],
        ),
    ]
